#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'timeConversion' function below.
#
# The function is expected to return a STRING.
# The function accepts STRING s as parameter.
#

def timeConversion(s):
    # Write your code here
    times = s.split(":")
    meridiem = times[2][-2]
    times[2] = times[2][0:2]

    
    #a[start:stop]  # items start through stop-1
    #a[start:]      # items start through the rest of the array
    #a[:stop]       # items from the beginning through stop-1    
    #a[:]           # a copy of the whole array
    
    if s[-2:] == "AM":
        if (times[0] == "12"):
            times[0] = "00"
            
        result = f"{times[0]}:{times[1]}:{times[2]}"
    else:
        if (times[0] == "12"):
            result = f"12:{times[1]}:{times[2]}"
        else:
        
            times[0] = str(int(times[0]) + 12)
            result = f"{times[0]}:{times[1]}:{times[2]}"

    return result

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = timeConversion(s)

    fptr.write(result + '\n')

    fptr.close()
